# Playbook is: A list of plays

- hosts: tags_items___db__
  name: Prepare storage for mysql
  become: yes
  tasks:
    - name: Create ext4 filesystem on the persistent disk
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-persistent-disk-1

    - name: Mount the persistent disk at /var/lib/mysql
      ansible.posix.mount:
        path: /var/lib/mysql
        src: /dev/disk/by-id/google-persistent-disk-1
        fstype: ext4
        state: mounted
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - mariadb-server
          - python3-pymysql
    - name: Grant all privileges to mediawiki user
      community.mysql.mysql_query:
        login_user: root
        query: "GRANT ALL ON mediawiki.* TO 'mediawiki'@'%' IDENTIFIED BY 'mediawiki';"
        login_unix_socket: /run/mysqld/mysqld.sock
    - name: Allow remote connections
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address            =0.0.0.0'
      notify: Restart MariaDB

  handlers:
    - name: Restart MariaDB
      ansible.builtin.service:
        name: mariadb
        state: restarted

- hosts: tags_items___web__
  name: Install Apache and PHP
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - mediawiki
          - python3-pymysql
    - name: Copy the google logging config
      ansible.builtin.copy:
        src: config.yaml
        dest: /etc/google-cloud-ops-agent/config.yaml
        owner: root
        group: root
        mode: '0644'
      notify: Restart logging

  handlers:
    - name: Restart logging
      ansible.builtin.service:
        name: google-cloud-ops-agent
        state: restarted